language: python
python:
- '2.7'
- '3.3'
- '3.4'
before_install:
- sudo add-apt-repository ppa:deluge-team/ppa -y
- sudo apt-get update
- sudo apt-get install libtorrent-rasterbar7=0.16.17-1ubuntu3~ppa1~precise
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then sudo apt-get install python-libtorrent
  python-dev; else sudo apt-get install python-libtorrent python3-dev; fi
install:
- sudo pip install coverage coveralls
- sudo python setup.py install
script:
- sudo coverage run setup.py test -a "--doctest-modules --pep8 -v tests/ storjtorrent/"
- coverage report -m --include="storjtorrent/*"
after_success:
- coveralls
notifications:
  slack:
    secure: Nx1lcl41YC3cB73D+vjJmHShVDLclPYGQI2+3+L21HCYK9SC6G2YW/BDAXA1Ens4kF9BnyHnD1+EGrKDMlHXy4ca4VqctAz0iNvZroqfrE+PIclZqwWxJzK3ZDlk5M+B+qVRFOizlkILPSpRhhhlUzTW6o/1wIrcmgkqHO/h65k=
